### ISSUE TITLE
Add KotlinFire

### ISSUE THREAD

**Issue by FlyingPig525** [BedCrabDev/MCDiamondFire-Awesome#32]
KotlinFire is a Kotlin library I am working on for template manipulation. I think it is very cool as it makes use of Kotlin lambdas, operator overloading, and extension functions, allowing for a pretty clean syntax. It is not finished and only has support for functions/processes, basic code blocks, and primitive types.

Repo: [KotlinFire](https://github.com/FlyingPig525/KotlinFire)

Currently the only way to use this library is to clone the repo and execute code through the test entry point. This will change soon once it becomes more refined.

**Comment by AstroSquared** [comment]
@FlyingPig525 I've made a PR to add this. If you'd like the entry tweaked, let me know, otherwise I will merge it tommorow.
