### ISSUE TITLE
Add rustfire

### ISSUE THREAD

**Issue by AstroSquared** [BedCrabDev/MCDiamondFire-Awesome#8]
note to people that want to use it: the maintainer has request that you **don't use until version 1.0.0 is released; syntax is changing frequently**

https://github.com/akarahdev/rustfire

**Comment by CheaterTim** [comment]
Rustfire had its last commit in february

**Comment by AstroSquared** [comment]
![image](https://github.com/BedCrabDev/MCDiamondFire-Awesome/assets/67833955/09106e10-6f4f-4d8d-a702-f695b4694e2f)

**Comment by AstroSquared** [comment]
wrong close type xdddd
